# Generated by Django 2.0.2 on 2018-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('summary', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
    ]
